In [81]:
''' end to end model development for credit card project '''

' end to end model development for credit card project '

In [82]:
import os
import sys
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings
warnings.filterwarnings('ignore')

**loading the data**

In [83]:
df = pd.read_csv('creditcard.csv')

**pre-processing stage**

In [84]:
df.sample(5)

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
67323,0.0,0.216771,62.0,Male,Central,7500.0,Rented,Non-officer,Professional,0.0,0.006399,7500.0,2.0,0.0,0.0,0.0,0.0,Good
57784,0.0,0.281163,47.0,Male,East,10433.0,Rented,Non-officer,Professional,0.0,0.271420,10433.0,13.0,0.0,1.0,0.0,2.0,Good
92927,0.0,0.000455,47.0,Male,Central,3000.0,Rented,Non-officer,Graduate,0.0,0.000000,3000.0,3.0,0.0,0.0,0.0,2.0,Good
88599,0.0,0.000000,63.0,Male,Central,15971.0,Rented,Self_Emp,Graduate,0.0,0.331768,15971.0,13.0,0.0,2.0,0.0,0.0,Good
29589,0.0,0.318508,70.0,Male,North,7000.0,Ownhouse,Non-officer,Graduate,0.0,0.463934,7000.0,24.0,0.0,3.0,0.0,0.0,Good

In [85]:
df.isnull().sum()

NPA Status                                  2
RevolvingUtilizationOfUnsecuredLines        2
age                                         2
Gender                                      2
Region                                      2
MonthlyIncome                           29733
Rented_OwnHouse                             2
Occupation                                  2
Education                                   2
NumberOfTime30-59DaysPastDueNotWorse        2
DebtRatio                                   2
MonthlyIncome.1                         29733
NumberOfOpenCreditLinesAndLoans             2
NumberOfTimes90DaysLate                     2
NumberRealEstateLoansOrLines                2
NumberOfTime60-89DaysPastDueNotWorse        2
NumberOfDependents                       3924
Good_Bad                                    2
dtype: int64

In [86]:
df.tail()

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
149997,0.0,0.246044,58.0,Male,North,NaN,Rented,Officer2,Professional,0.0,3870.000000,NaN,18.0,0.0,1.0,0.0,0,Good
149998,0.0,0.000000,30.0,Male,North,5716.0,Rented,Non-officer,Professional,0.0,0.000000,5716.0,4.0,0.0,0.0,0.0,0,Good
149999,0.0,0.850283,64.0,Male,North,8158.0,Ownhouse,Self_Emp,Professional,0.0,0.249908,8158.0,8.0,0.0,2.0,0.0,0,Good
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

**when we observe the last 2 rows all columns are nul values,so there is no problem in deleting the last two rows**

In [87]:
df = df.drop([150000,150001],axis=0)
df.tail()

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
149995,0.0,0.040674,74.0,Male,North,2100.0,Ownhouse,Non-officer,Professional,0.0,0.225131,2100.0,4.0,0.0,1.0,0.0,0,Good
149996,0.0,0.299745,44.0,Male,North,5584.0,Ownhouse,Self_Emp,Professional,0.0,0.716562,5584.0,4.0,0.0,1.0,0.0,2,Good
149997,0.0,0.246044,58.0,Male,North,NaN,Rented,Officer2,Professional,0.0,3870.000000,NaN,18.0,0.0,1.0,0.0,0,Good
149998,0.0,0.000000,30.0,Male,North,5716.0,Rented,Non-officer,Professional,0.0,0.000000,5716.0,4.0,0.0,0.0,0.0,0,Good
149999,0.0,0.850283,64.0,Male,North,8158.0,Ownhouse,Self_Emp,Professional,0.0,0.249908,8158.0,8.0,0.0,2.0,0.0,0,Good

In [88]:
df.isnull().sum()

NPA Status                                  0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
Gender                                      0
Region                                      0
MonthlyIncome                           29731
Rented_OwnHouse                             0
Occupation                                  0
Education                                   0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome.1                         29731
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3924
Good_Bad                                    0
dtype: int64

In [89]:
X = df.iloc[: , :-1]
y = df.iloc[: ,-1]

In [90]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=2)

In [91]:
len(X_train),len(y_train)

(135000, 135000)

In [92]:
len(X_test),len(y_test)

(15000, 15000)

**when we observe columns,we can two similar column names "MonthlyIncome" and "MonthlyIncome.1".Let' check whether both values are same or not**

In [93]:
X_train.index

Index([ 83022,  95205, 100780,   6760, 143321, 130148, 121680,  44409, 148743,
       114354,
       ...
        35541,  43595,  33201,  53922,  80232,  33867,  84434,  95816, 100879,
        89256],
      dtype='int64', length=135000)

In [94]:
#comparing "MonthlyIncome" and "MonthlyIncome.1"
c=[]
for i in X_train.index:
  if np.isnan(X_train["MonthlyIncome"][i]) == np.isnan(X_train["MonthlyIncome.1"][i]):
    pass
  elif df["MonthlyIncome"][i] == df["MonthlyIncome.1"][i]:
    pass
  else:
    c.append(i)
print(c)

[]

**from the above result,we can say that both columns are same.so, we can remove one of the columns**

In [95]:
X_train = X_train.drop(['MonthlyIncome.1'],axis=1)
X_test = X_test.drop(['MonthlyIncome.1'],axis=1)

In [96]:
X_train.isnull().sum()

NPA Status                                  0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
Gender                                      0
Region                                      0
MonthlyIncome                           26839
Rented_OwnHouse                             0
Occupation                                  0
Education                                   0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3529
dtype: int64